title: Hi, I'm Alex!
# logo: /assets/img/me_round.png
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme
